// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  owner, blance, currency
) VALUES (
  $1, $2, $3
)
RETURNING id, owner, blance, currency, created_at
`

type CreateAccountParams struct {
	Owner    string `json:"owner"`
	Blance   int64  `json:"blance"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Owner, arg.Blance, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Blance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
